### ISSUE TITLE
[REQUEST] Niagara Assets

### ISSUE THREAD

**Issue by AeptaX** [GMatrixGames/JsonAsAsset#33]
## [Niagara Asset Request]

I think Niagara support for JAA would be really useful so it'd be cool to see it added if possible

**Comment by ikonikisop** [comment]
It's Possible, but as Tector said he does not want to spend weeks on end adding support for that.
![image](https://github.com/GMatrixGames/JsonAsAsset/assets/129855365/3f196cb6-fe69-447a-9461-1f7e2f234ab2)

**Comment by Tectors** [comment]
at the moment, it's not coming to JsonAsAsset
