### ISSUE TITLE
Crash Importing DataAsset in UE 5.1.1

### ISSUE THREAD

**Issue by Doctor-Duck** [GMatrixGames/JsonAsAsset#38]
Hello,

I attempted to import a DataAsset from an extracted .JSON file, and I am getting a crash when it happens.

Here is the crash report:
![image](https://github.com/GMatrixGames/JsonAsAsset/assets/84234068/185a1bed-ad92-421a-a43d-edf58b27675d)

And here is the .JSON file I tried importing: https://mega.nz/file/QJMSAZzD#fd8kMrB3Gm6a7chHaB8imUbqjmh6ACrEoRnBfi4GjHg

**Comment by GMatrixGames** [comment]
It's been a while, but I'm fairly sure the DataAsset importer doesn't support subobjects.

**Comment by Doctor-Duck** [comment]
> It's been a while, but I'm fairly sure the DataAsset importer doesn't support subobjects.

Any idea how I can import this then? Or a suggestion on how I edit the DataAsset the .JSON comes from?

**Comment by GMatrixGames** [comment]
Best option is always manual replication.
Grab an SDK dump, recreate the cpp assets classes, and manually enter the data in
