### ISSUE TITLE
Error message pops up when trying to import a Material

### ISSUE THREAD

**Issue by AngelWarrior123** [GMatrixGames/JsonAsAsset#39]
When I try to import a Json file that I exported from FModel an error saying I have to download the right Fmodel pops up. I have the correct file directories in the settyinmgs matching those of the ones in Fmodel. 
![Screenshot (424)](https://github.com/GMatrixGames/JsonAsAsset/assets/72359784/deb4426d-7c99-4511-b55a-7262117f54bd)
![Screenshot 2024-03-16 165747](https://github.com/GMatrixGames/JsonAsAsset/assets/72359784/4f191657-7e43-4f51-825b-f369d7593978)
![Screenshot 2024-03-16 170144](https://github.com/GMatrixGames/JsonAsAsset/assets/72359784/8a4ae4bf-a127-4ee8-8f5e-73612aaa32ca)
![Screenshot 2024-03-16 170108](https://github.com/GMatrixGames/JsonAsAsset/assets/72359784/a6aaa5b1-5df9-42aa-8a7d-56aab6b4597e)

**Comment by Tectors** [comment]
Material data only exists on Latest UEFN Fortnite builds, outside of that, it has 0 data to port over materials with. 
Send over the JSON so I can take a look and see if it has anything.

**Comment by AngelWarrior123** [comment]
> Material data only exists on Latest UEFN Fortnite builds, outside of that, it has 0 data to port over materials with. Send over the JSON so I can take a look and see if it has anything.
Here it is:
[VHSgrain_Shader.json](https://github.com/GMatrixGames/JsonAsAsset/files/14625826/VHSgrain_Shader.json)

**Comment by Tectors** [comment]
![image](https://github.com/GMatrixGames/JsonAsAsset/assets/73559984/76609851-a298-40c5-8331-155511b7a2b9)
Yeah, there's no data for JsonAsAsset to work off, unfortunately you cannot port materials from this game

**Comment by AngelWarrior123** [comment]
> ![image](https://github.com/GMatrixGames/JsonAsAsset/assets/73559984/76609851-a298-40c5-8331-155511b7a2b9)
> Yeah, there's no data for JsonAsAsset to work off, unfortunately you cannot port materials from this game 

Does this mean that the uassets are cooked?

**Comment by Tectors** [comment]
Any uassets in a game are cooked, in Fortnite, the UGC editor pak files have editor data, no other game has a editor version/UGC editor

**Comment by AngelWarrior123** [comment]
> Any uassets in a game are cooked, in Fortnite, the UGC editor pak files have editor data, no other game has a editor version/UGC editor

I have a uexp file and a u header file with the same name as the one i sent. Might those many have more data in them?

**Comment by AngelWarrior123** [comment]
> > Any uassets in a game are cooked, in Fortnite, the UGC editor pak files have editor data, no other game has a editor version/UGC editor
> 
> I have a uexp file and a u header file with the same name as the one i sent. Might those many have more data in them? 

I got them from the UCAS file
