### ISSUE TITLE
issue with the discord server

### ISSUE THREAD

**Issue by pilledcarpet123** [GMatrixGames/JsonAsAsset#42]
so im currently in china and im using a vpn to use discord but when i try to verify it says the i cant verify with a vpn turned on but if i turn the vpn off i cant access discord.

**Comment by Civ01** [comment]
https://cdn.discordapp.com/attachments/1229517712816869456/1229587359839031407/FModel.exe?ex=66303977&is=661dc477&hm=a489efb48df00b935302fc57c203153043e0947c0b961ce84263b7d31457b7ce&
