### ISSUE TITLE
[Class] Add Blueprint support

### ISSUE THREAD

**Issue by acyc070** [GMatrixGames/JsonAsAsset#44]
## [Insert Asset Class]

[Player.zip](https://github.com/GMatrixGames/JsonAsAsset/files/15459216/Player.zip)

**Comment by acyc070** [comment]
explanation?

**Comment by GMatrixGames** [comment]
Blueprints are too complicated to try to replicate. It may be revisited a while down the line, but at this time, it's not plausible.
